server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys
    username: root
    password: srivatsan
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate: info

